/*
hsm2
*/
/*DROP DATABASE IF EXISTS hsm2;
CREATE DATABASE hsm2;*/
USE hsm2;

DROP TABLE IF EXISTS LD_Block;
DROP TABLE IF EXISTS RefSNPpairs;
DROP TABLE IF EXISTS SNP;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS annotationIDpairs;
DROP TABLE IF EXISTS geneIDpairs;

CREATE TABLE LD_Block
(
Ref_SNP				VARCHAR(100)		NOT NULL,
chr				VARCHAR(6)		NOT NULL,
start				INT			NOT NULL,
stop				INT			NOT NULL,
PRIMARY KEY (Ref_SNP)
)ENGINE = INNODB;

CREATE TABLE RefSNPpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
Ref_SNP		VARCHAR (100)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE SNP
(
SNP	VARCHAR(100)	NOT NULL,
chr	VARCHAR(6)	NOT NULL,
start	INT		NOT NULL,
stop	INT		NOT NULL,
PRIMARY KEY (SNP)
)ENGINE = INNODB;

CREATE TABLE files
(
id		INT		NOT NULL	AUTO_INCREMENT,
SNP		VARCHAR(100)	NOT NULL,
1DISC_graph_png	VARCHAR(500)	NOT NULL,
1DISC_dataFile	VARCHAR(500)	NOT NULL,
1DISC_graph_pdf	VARCHAR(500)	NOT NULL,
2FOLL_graph_png	VARCHAR(500)	NOT NULL,
2FOLL_dataFile	VARCHAR(500)	NOT NULL,
2FOLL_graph_pdf	VARCHAR(500)	NOT NULL,
3REPL_graph_png	VARCHAR(500)	NOT NULL,
3REPL_dataFile	VARCHAR(500)	NOT NULL,
3REPL_graph_pdf	VARCHAR(500)	NOT NULL,
vALL_graph_png	VARCHAR(500)	NOT NULL,
vALL_dataFile	VARCHAR(500)	NOT NULL,
vALL_graph_pdf	VARCHAR(500)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE annotationIDpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
annotation	VARCHAR(1000)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE geneIDpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
gene		VARCHAR(100)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

