/*
hsm2
*/
DROP DATABASE IF EXISTS hsm2;
CREATE DATABASE hsm2;
USE hsm2;

CREATE TABLE LD_Block
(
Ref_SNP				VARCHAR(100)		NOT NULL,
chr				VARCHAR(6)		NOT NULL,
start				INT			NOT NULL,
stop				INT			NOT NULL,
PRIMARY KEY (Ref_SNP)
)ENGINE = INNODB;

CREATE TABLE RefSNPpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
Ref_SNP		VARCHAR (100)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE SNP
(
SNP	VARCHAR(100)	NOT NULL,
chr	VARCHAR(6)	NOT NULL,
start	INT		NOT NULL,
stop	INT		NOT NULL,
PRIMARY KEY (SNP)
)ENGINE = INNODB;

CREATE TABLE files
(
id		INT		NOT NULL	AUTO_INCREMENT,
SNP		VARCHAR(100)	NOT NULL,
dataFilename	VARCHAR(500)	NOT NULL,
pValFilename	VARCHAR(500)	NOT NULL,
pValPDFfilename	VARCHAR(500)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE annotationIDpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
annotation	VARCHAR(1000)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE geneIDpairs
(
id		INT		NOT NULL	AUTO_INCREMENT,
gene		VARCHAR(100)	NOT NULL,
SNP		VARCHAR(100)	NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

